name: Backend CI (Linter)

on:
  push:
    
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do Repositório
      uses: actions/checkout@v4

    - name: Configurar Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
        cache: 'pip'

    - name: Instalar Dependências e Linters
      working-directory: ./backend
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Verificar formatação com Black
      working-directory: ./backend
      run: |
        black --check app/

    - name: Analisar código com Flake8
      working-directory: ./backend
      run: |
        flake8 app/ --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 app/ --count --extend-ignore=E501 --max-complexity=10 --max-line-length=88 --statistics